name: Workflow for main application

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:

  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.29

  build:
    needs: lint
    name: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Golang
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
    - name: Build
      run: go build -v ./...

  test:
    needs: build
    name: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Golang
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
    - name: Test
      run: go test -v ./...
  
  docker:
    needs: test
    name: docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - name: Docker build 
        uses: docker/build-push-action@v3
        with:
          context: "build/package"
          push: false
